name: Maven Test and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.latesttag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install dependencies
        run: mvn install

      - name: Run Maven tests
        run: mvn test

      - name: Get Latest Tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: v1.0.0

      - name: Build Docker image
        if: success()
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/eshop-back:${{ steps.latesttag.outputs.tag }} -t ${{ secrets.DOCKER_USERNAME }}/eshop-back:latest .

      - name: Log in to Docker Hub
        if: success()
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eshop-back --all-tags

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout external repository
        uses: actions/checkout@v2
        with:
          repository: distributed-systems-ds/deployment-config
          ref: "main"
          path: eshop-deployment
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Update values.yml with new tag
        run: |
          cd eshop-deployment/eshop-back
          sed -i 's/image: .*/image: "danieljaraba/eshop-back:${{ needs.build.outputs.release-tag }}"/' values.yaml
          git config --global user.email "${{ secrets.DOCKER_USERNAME }}"
          git config --global user.name "${{ secrets.DOCKER_USERNAME }}"
          git add values.yaml
          git commit -m "Update image tag to ${{ needs.build.outputs.release-tag }}"
          git push
